[build]
  publish = "build"
  command = "npm run build"

# Handle auth callback specifically (must come before catch-all)
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

# Handle API routes (if any)
[[redirects]]
  from = "/api/*"
  to = "https://node-backend-1-21an.onrender.com/api/:splat"
  status = 200

# Catch-all for SPA routing (must come last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
